services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: padelcoach
      POSTGRES_PASSWORD: padelcoach123
      POSTGRES_DB: padelcoach_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
    working_dir: /app
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - PYTHONWARNINGS=default
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    env_file:
      - ./server/.env
    command: flask run --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - backend

volumes:
  postgres_data:
