services:
  db:
    image: postgres:14
    container_name: padelcoach_db
    restart: always
    environment:
      POSTGRES_USER: padelcoach
      POSTGRES_PASSWORD: padelcoach123
      POSTGRES_DB: padelcoach_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    container_name: padelcoach_backend
    command: python run.py
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client  
    container_name: padelcoach_frontend
    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: