"""empty message

Revision ID: bd130727ac06
Revises: ccc1288d884d
Create Date: 2025-04-02 10:39:01.321332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd130727ac06'
down_revision = 'ccc1288d884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('sessions_trainer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainers', ['trainer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sessions_trainer_id_fkey', 'users', ['trainer_id'], ['id'])

    # ### end Alembic commands ###
