"""empty message

Revision ID: c11c05d561b2
Revises: bd130727ac06
Create Date: 2025-04-02 12:00:22.814938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c11c05d561b2'
down_revision = 'bd130727ac06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_type', sa.Enum('indoor', 'outdoor', name='court_type_enum'), nullable=False))
        batch_op.drop_column('type')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('indoor', 'outdoor', name='court_type_enum'), autoincrement=False, nullable=False))
        batch_op.drop_column('court_type')

    # ### end Alembic commands ###
